name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PNPM_CONFIG_FROZEN_LOCKFILE: false
    strategy:
      fail-fast: false
      matrix:
        zod: ['3', '4']
        firebase: ['12']
        firebase_admin: ['12', '13']
    name: tests (zod@${{ matrix.zod }}, firebase@${{ matrix.firebase }}, firebase-admin@${{ matrix.firebase_admin }})
    steps:
      - uses: actions/checkout@v5
      - name: cache firebase emulator
        uses: actions/cache@v4
        with:
          path: .cache/firebase
          key: ${{ runner.os }}-firebase-emulator

      - name: setup pnpm
        uses: valian-ca/github-workflows/.github/actions/setup-pnpm@main
      - name: Install zod@^${{ matrix.zod }} at workspace root
        run: pnpm add -Dw zod@^${{ matrix.zod }}
      - name: Install firebase@^${{ matrix.firebase }} for zod-firebase
        run: pnpm add -Dw firebase@^${{ matrix.firebase }}
      - name: Install firebase-admin@^${{ matrix.firebase_admin }} for zod-firebase-admin
        run: pnpm add -Dw firebase-admin@^${{ matrix.firebase_admin }}
      - name: dedupe
        run: pnpm dedupe
      - name: tests
        run: pnpm test
      - name: Upload zod-firebase Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          directory: ./packages/zod-firebase/test-results
          flags: zod-${{ matrix.zod }}_firebase-${{ matrix.firebase }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin Test Results to Codecov
        uses: codecov/test-results-action@v1
        with:
          directory: ./packages/zod-firebase-admin/test-results
          flags: zod-${{ matrix.zod }}_firebase-admin-${{ matrix.firebase_admin }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload zod-firebase coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase/coverage
          flags: zod-${{ matrix.zod }}_firebase-${{ matrix.firebase }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload zod-firebase-admin coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./packages/zod-firebase-admin/coverage
          flags: zod-${{ matrix.zod }}_firebase-admin-${{ matrix.firebase_admin }}
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Set up Java for firebase emulators
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '21'
      - name: integration tests
        run: pnpm run test:integration:ci
